### ISSUE TITLE
HOBBIES area are not flexible 

### ISSUE THREAD

**Issue by yossigruner** [yossigruner/ResuMate#1]
When you filled more the one line of hobbies the hobbies area are not expended

**Comment by oronbz** [comment]
Hello @yossigruner  please learn to read placeholders:
`Hobbies seperated by commas`

**Comment by oronbz** [comment]
Sorry mr. @yossigruner I misunderstood you

**Comment by oronbz** [comment]
Hello mr. @yossigruner you lazy bastard, please make sure that next time you actually insert hobbies and not empty ones!
